#!/usr/bin/env python
# coding: utf-8

# In[4]:


import torch
import torch.nn as nn
import torchvision.transforms as transforms
import torch.optim as optim
import torchvision.datasets as datasets
import imageio
import numpy as np
import matplotlib
from torchvision.utils import make_grid, save_image
from torch.utils.data import DataLoader
from matplotlib import pyplot as plt
from tqdm import tqdm
matplotlib.style.use('ggplot')


# ## Defining the Learning Parameters

# In[5]:


# learning parameters
batch_size = 512
epochs = 200
sample_size = 64 # fixed sample size
nz = 128 # latent vector size
k = 1 # number of steps to apply to the discriminator
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')


# ## Preparing the Dataset

# In[6]:


transform = transforms.Compose([
                                transforms.ToTensor(),
                                transforms.Normalize((0.5,),(0.5,)),
])
to_pil_image = transforms.ToPILImage()


# #### download the dataset, change the second line, delete "..“

# In[7]:


train_data = datasets.MNIST(
    root='input/data',
    train=True,
    download=True,
    transform=transform
)
train_loader = DataLoader(train_data, batch_size=batch_size, shuffle=True)


# ## The Generator Neural Network

# In[8]:


class Generator(nn.Module):
    def __init__(self, nz):
        super(Generator, self).__init__()
        self.nz = nz
        self.main = nn.Sequential(
            nn.Linear(self.nz, 256),
            nn.LeakyReLU(0.2),
            nn.Linear(256, 512),
            nn.LeakyReLU(0.2),
            nn.Linear(512, 1024),
            nn.LeakyReLU(0.2),
            nn.Linear(1024, 784),
            nn.Tanh(),
        )
    def forward(self, x):
        return self.main(x).view(-1, 1, 28, 28)


# ## The Discriminator Neural Network

# In[9]:


class Discriminator(nn.Module):
    def __init__(self):
        super(Discriminator, self).__init__()
        self.n_input = 784
        self.main = nn.Sequential(
            nn.Linear(self.n_input, 1024),
            nn.LeakyReLU(0.2),
            nn.Dropout(0.3),
            nn.Linear(1024, 512),
            nn.LeakyReLU(0.2),
            nn.Dropout(0.3),
            nn.Linear(512, 256),
            nn.LeakyReLU(0.2),
            nn.Dropout(0.3),
            nn.Linear(256, 1),
            nn.Sigmoid(),
        )
    def forward(self, x):
        x = x.view(-1, 784)
        return self.main(x)


# ## Initialize the Neural Networks and Define the Optimizers

# In[10]:


generator = Generator(nz).to(device)
discriminator = Discriminator().to(device)
print('##### GENERATOR #####')
print(generator)
print('######################')
print('\n##### DISCRIMINATOR #####')
print(discriminator)
print('######################')


# In[11]:


# optimizers
optim_g = optim.Adam(generator.parameters(), lr=0.0002)
optim_d = optim.Adam(discriminator.parameters(), lr=0.0002)


# In[12]:


# loss function
criterion = nn.BCELoss()


# In[13]:


losses_g = [] # to store generator loss after each epoch
losses_d = [] # to store discriminator loss after each epoch
images = [] # to store images generatd by the generator


# ## Defining Some Utility Functions

# In[14]:


# to create real labels (1s)
def label_real(size):
    data = torch.ones(size, 1)
    return data.to(device)
# to create fake labels (0s)
def label_fake(size):
    data = torch.zeros(size, 1)
    return data.to(device)


# In[15]:


# function to create the noise vector
def create_noise(sample_size, nz):
    return torch.randn(sample_size, nz).to(device)


# In[16]:


# to save the images generated by the generator
def save_generator_image(image, path):
    save_image(image, path)


# ## Function to Train the Discriminator

# In[17]:


# function to train the discriminator network
def train_discriminator(optimizer, data_real, data_fake):
    b_size = data_real.size(0)
    real_label = label_real(b_size)
    fake_label = label_fake(b_size)
    optimizer.zero_grad()
    output_real = discriminator(data_real)
    loss_real = criterion(output_real, real_label)
    output_fake = discriminator(data_fake)
    loss_fake = criterion(output_fake, fake_label)
    loss_real.backward()
    loss_fake.backward()
    optimizer.step()
    return loss_real + loss_fake


# ## Function to Train the Generator

# In[18]:


# function to train the generator network
def train_generator(optimizer, data_fake):
    b_size = data_fake.size(0)
    real_label = label_real(b_size)
    optimizer.zero_grad()
    output = discriminator(data_fake)
    loss = criterion(output, real_label)
    loss.backward()
    optimizer.step()
    return loss


# ## Training the GAN

# In[19]:


# create the noise vector
noise = create_noise(sample_size, nz)


# In[20]:


generator.train()
discriminator.train()


# ## The Training Loop

# #### Changed the file name

# In[21]:


for epoch in range(epochs):
    loss_g = 0.0
    loss_d = 0.0
    for bi, data in tqdm(enumerate(train_loader), total=int(len(train_data)/train_loader.batch_size)):
        image, _ = data
        image = image.to(device)
        b_size = len(image)
        # run the discriminator for k number of steps
        for step in range(k):
            data_fake = generator(create_noise(b_size, nz)).detach()
            data_real = image
            # train the discriminator network
            loss_d += train_discriminator(optim_d, data_real, data_fake)
        data_fake = generator(create_noise(b_size, nz))
        # train the generator network
        loss_g += train_generator(optim_g, data_fake)
    # create the final fake image for the epoch
    generated_img = generator(noise).cpu().detach()
    # make the images as grid
    generated_img = make_grid(generated_img)
    # save the generated torch tensor models to disk
     save_generator_image(generated_img, f"C:/Users/84592/Desktop/mnist-trans-gan/output/gen_img{epoch}.png")
    # save_generator_image(generated_img, f"/graphganvol/anni/mnist/output/gen_img{epoch}.png")
    images.append(generated_img)
    epoch_loss_g = loss_g / bi # total generator loss for the epoch
    epoch_loss_d = loss_d / bi # total discriminator loss for the epoch
    losses_g.append(epoch_loss_g)
    losses_d.append(epoch_loss_d)
    
    print(f"Epoch {epoch} of {epochs}")
    print(f"Generator loss: {epoch_loss_g:.8f}, Discriminator loss: {epoch_loss_d:.8f}")


# ## The Final Steps

# In[22]:


print('DONE TRAINING')
C:/Users/84592/Desktop/mnist-trans-gan/output
torch.save(generator.state_dict(), 'C:/Users/84592/Desktop/mnist-trans-gan/output/generator.pth')
# torch.save(generator.state_dict(), '/graphganvol/anni/mnist/output/generator.pth')


# In[23]:


# save the generated images as GIF file
imgs = [np.array(to_pil_image(img)) for img in images]

imageio.mimsave('C:/Users/84592/Desktop/mnist-trans-gan/output/out.gif', imgs)
# imageio.mimsave('/graphganvol/anni/mnist/output/out.gif', imgs)


# In[24]:


lossg = []
lossd = []
for i in losses_g:
    i = i.cpu().detach().numpy()
    lossg.append(i)
    
for k in losses_d:
    k = k.cpu().detach().numpy()
    lossd.append(k)


# In[26]:


# plot and save the generator and discriminator loss
plt.figure()
plt.plot(lossg, label='Generator loss')
plt.plot(lossd, label='Discriminator Loss')
plt.legend()
plt.savefig('C:/Users/84592/Desktop/mnist-trans-gan/output/loss.png')
# plt.savefig('/graphganvol/anni/mnist/output/loss.png')

